import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import "./globals.css";
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Providers } from "@/components/ui/providers";

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const ibm_plex_mono = IBM_Plex_Mono({
  weight: ["400","500","600","700"],
  variable: "--font-flex-mono",
  subsets: ["latin"]
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${ibm_plex_mono.variable} antialiased`}
      >
            <Providers>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
                {children}
            </Providers>
      </body>
    </html>
  );
}
